'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class addtime

    '''<summary>
    '''LBL_Info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_Info As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Employees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Employees As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DDL_Employee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_Employee As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RB_SingleDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RB_SingleDay As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RB_MultiDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RB_MultiDay As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Panel_SingleDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_SingleDay As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TXT_StartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_StartDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDL_StartTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_StartTime As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TXT_EndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_EndDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDL_EndTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_EndTime As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Panel_MultiDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_MultiDay As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TXT_StartDateMulti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_StartDateMulti As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_EndDateMulti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_EndDateMulti As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDL_StartTimeMulti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_StartTimeMulti As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDL_EndTimeMulti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_EndTimeMulti As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SDS_PMs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SDS_PMs As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DDL_PM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_PM As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDL_State control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_State As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TXT_JobNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_JobNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDL_PW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_PW As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TXT_Project control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_Project As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDL_ShiftType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_ShiftType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDL_Travel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_Travel As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDL_PerDiem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_PerDiem As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDL_Injured control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_Injured As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TXT_Comments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_Comments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BTN_Submit1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_Submit1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTN_Cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_Cancel As Global.System.Web.UI.WebControls.Button
End Class
