'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class employees

    '''<summary>
    '''LBL_Info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_Info As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_employeelist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_employeelist As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''SDS_EmployeeList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SDS_EmployeeList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''GW_EmployeeList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GW_EmployeeList As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Panel_EditUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_EditUser As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LIT_Heading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LIT_Heading As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Panel_UsernameBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_UsernameBox As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TXT_Username control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_Username As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel_UsernameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_UsernameLabel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LIT_Username control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LIT_Username As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''TXT_Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_Email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_password As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_firstname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_firstname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_LastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_LastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_Initials control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_Initials As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_Cellphone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_Cellphone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SDS_Offices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SDS_Offices As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DDL_Office control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_Office As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDL_Department control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_Department As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDL_Type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_Type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDL_EmployeeGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_EmployeeGroup As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CHK_Worker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CHK_Worker As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CHK_PartTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CHK_PartTime As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CHK_PM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CHK_PM As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CHK_Clerk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CHK_Clerk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CHK_Active control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CHK_Active As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CHK_ReadOnlyAccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CHK_ReadOnlyAccess As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CHK_LimitedView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CHK_LimitedView As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''TXT_PerDiem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_PerDiem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_TravelCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_TravelCompany As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_TravelPersonal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_TravelPersonal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_PayrollID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_PayrollID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BTN_Submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_Submit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTN_Cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_Cancel As Global.System.Web.UI.WebControls.Button
End Class
