'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class landing

    '''<summary>
    '''DDL_DateRange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_DateRange As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SDS_Office control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SDS_Office As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DDL_Office control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_Office As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LIT_Main control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LIT_Main As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LIT_OfficeTotals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LIT_OfficeTotals As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LIT_UnprocessedWarnings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LIT_UnprocessedWarnings As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BTN_Payroll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_Payroll As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTN_Lock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_Lock As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTN_Unlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_Unlock As Global.System.Web.UI.WebControls.Button
End Class
