'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class report_timebyjob

    '''<summary>
    '''SDS_Users control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SDS_Users As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''TXT_StartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_StartDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_EndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_EndDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDL_User control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_User As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''BTN_SubmitDates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_SubmitDates As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LIT_Results control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LIT_Results As Global.System.Web.UI.WebControls.Literal
End Class
