'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class timesheets2

    '''<summary>
    '''LIT_SyncData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LIT_SyncData As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LIT_DatesDropDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LIT_DatesDropDown As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''DDL_DateRange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_DateRange As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDL_Offices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_Offices As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDL_Type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_Type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDL_ShowAsPM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_ShowAsPM As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LIT_WorkerList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LIT_WorkerList As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LIT_ReportLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LIT_ReportLink As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LIT_ProjectList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LIT_ProjectList As Global.System.Web.UI.WebControls.Literal
End Class
